# Terminal color setting
export TERM="xterm-256color"
# Laguage settings
export LANG=de_DE.UTF-8
export LC_COLLATE=C
export LC_CTYPE=de_DE.UTF-8
export LC_NUMERIC=C

# History
#SAVEHIST=1000
HISTFILE=~/.zsh_history

# Prompt
# see ~/.config/starship.toml for configuration
eval "$(starship init zsh)"

zstyle ':completion:*' special-dirs true

# Alias
source ~/.config/zsh/zsh_aliases

autoload -Uz compinit
compinit

# Source plugins
# broot
source ~/.config/broot/launcher/bash/br
# zsh-autosuggestions
source ~/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
# sudo
source ~/.config/zsh/plugins/sudo/sudo.plugin.zsh
# systemd
source ~/.config/zsh/plugins/systemd/systemd.plugin.zsh
# gitfast
source ~/.config/zsh/plugins/gitfast/gitfast.plugin.zsh
# golang
source ~/.config/zsh/plugins/golang/golang.plugin.zsh
# fzf
source ~/.config/zsh/plugins/fzf/fzf.plugin.zsh
# ssh-agent
source ~/.config/zsh/plugins/ssh-agent/ssh-agent.plugin.zsh
# extract
source ~/.config/zsh/plugins/extract/extract.plugin.zsh
# zsh_reload
source ~/.config/zsh/plugins/zsh_reload/zsh_reload.plugin.zsh


# Autosuggestion settings
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=244'

freload() { while (( $# )); do; unfunction $1; autoload -U $1; shift; done }

# Where to look for autoloaded function definitions
fpath=(~/.config/zsh/zfunc/ $fpath)

# Autoload all shell functions from all directories in $fpath (following
# symlinks) that have the executable bit on (the executable bit is not
# necessary, but gives you an easy way to stop the autoloading of a
# particular shell function). $fpath should not be empty for this to work.
for func in $^fpath/*(N-.x:t); autoload $func

# automatically remove duplicates from these arrays
typeset -U path cdpath fpath manpath

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

