#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# This file's true location is in ~/.config/xprofile and a link exists to it in
# ~/.xprofile. If you do not use a DM, you may remove the link to it to have a
# cleaner home.

autostart="mpd dunst unclutter"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

#remaps &		# run the remaps script, switching caps/esc and more; check it for more info
~/.config/wpg/wp_init.sh & # set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
picom -fb &          # xcompmgr for transparency
xset r rate 360 40 & # Speed xrate up
setxkbmap -layout de & # Set German keyboard layout
