#!/bin/bash -
#===============================================================================
#
#          FILE: ytrssadd.sh
#
#         USAGE: ./ytrssadd.sh
#
#   DESCRIPTION: fetch youtube rss id and ad it to newsboat
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Dustin Hutto (Sysadmin), huttodustin@gmail.com
#  ORGANIZATION: -
#       CREATED: 12.04.2019 15:40:17
#      REVISION:  ---
#===============================================================================

set -o nounset                                  # Treat unset variables as an error

ytid=$(curl -s "$QUTE_URL" | tr " " "\n" | awk -F'"' '/data-channel-external-id=/{print $(NF-1);exit;}')
rssurl="https://www.youtube.com/feeds/videos.xml?channel_id=$ytid"

! echo "$rssurl" | grep "https*://\S\+\.[A-Za-z]\+\S*" >/dev/null &&
	notify-send "That doesn't look like a full URL." && exit
RSSFILE="$HOME/.config/newsboat/urls"
if awk '{print $rssurl}' "$RSSFILE" | grep "^$rssurl$" >/dev/null; then
	notify-send "You already have this RSS feed."
else
	echo "$rssurl" >> "$RSSFILE" && notify-send "RSS feed added."
fi
